spring:
  kafka:
    bootstrap-servers: plaintext://13.124.124.92:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  influx:
    user: ahyeon
    url: 54.180.117.54:8086
    password: 12wq12wq!
    token: Ook-BIskxsxeW116i3DsDop9wSus-90AWPX68HPiG1T1_N6ZW-_soljGI4fTG2EH5FrNAeFTwDpgPPYnvs5rGQ==


---
spring:
  config:
    activate:
      on-profile: client1

server:
  port: 8080

client:
  name: "CLIENT1"
---
spring:
  config:
    activate:
      on-profile: client2

server:
  port: 8081

client:
  name: "CLIENT2"
---
spring:
  config:
    activate:
      on-profile: client3

server:
  port: 8082

client:
  name: "CLIENT3"
