spring:
  kafka:
    bootstrap-servers: plaintext://13.124.124.92:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

---
spring:
  config:
    activate:
      on-profile: client1

server:
  port: 8080

client:
  name: "CLIENT1"
---
spring:
  config:
    activate:
      on-profile: client2

server:
  port: 8081

client:
  name: "CLIENT2"
---
spring:
  config:
    activate:
      on-profile: client3

server:
  port: 8082

client:
  name: "CLIENT3"
---
spring:
  config:
    activate:
      on-profile: client4

server:
  port: 8083

client:
  name: "CLIENT4"
---
spring:
  config:
    activate:
      on-profile: client5

server:
  port: 8084

client:
  name: "CLIENT5"
---
spring:
  config:
    activate:
      on-profile: client6

server:
  port: 8085

client:
  name: "CLIENT6"