spring:
  kafka:
    bootstrap-servers: plaintext://52.78.228.163:9092,plaintext://3.37.28.212:9092,plaintext://3.38.173.68:9092,plaintext://3.34.43.153:9092,plaintext://52.78.98.144:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
