spring:
  kafka:
    bootstrap-servers: plaintext://3.38.170.144:9092,plaintext://43.201.43.35:9092,plaintext://15.164.235.229:9092,plaintext://3.34.43.153:9092,plaintext://52.78.98.144:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
