netty:
  host: "127.0.0.1"
  data-port: 9997
  analog-port: 9998
  image-port: 9999

spring:
  profiles:
    active: client1


---
spring:
  config:
    activate:
      on-profile: client1

server:
  port: 8080

client:
  name: "SERVER1"
---
spring:
  config:
    activate:
      on-profile: client2

server:
  port: 8081

client:
  name: "SERVER2"
---
spring:
  config:
    activate:
      on-profile: client3

server:
  port: 8082

client:
  name: "SERVER3"
