spring:
  kafka:
    bootstrap-servers: plaintext://54.180.130.90:9092,plaintext://3.38.186.82:9092,plaintext://43.201.41.201:9092,plaintext://3.34.43.153:9092,plaintext://52.78.98.144:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer