spring:
  kafka:
    bootstrap-servers: plaintext://3.36.14.134:9092,plaintext://15.164.240.60:9092,plaintext://3.36.15.111:9092,plaintext://3.34.43.153:9092,plaintext://52.78.98.144:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
