spring:
  kafka:
    bootstrap-servers: plaintext://43.200.71.179:9092,plaintext://3.36.10.145:9092,plaintext://43.200.130.111:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
