spring:
  kafka:
    bootstrap-servers: plaintext://3.38.164.6:9092,plaintext://3.34.254.10:9092,plaintext://15.165.7.7:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
