spring:
  kafka:
    bootstrap-servers: plaintext://3.35.225.215:9092,plaintext://43.200.129.201:9092,plaintext://15.164.209.217:9092,plaintext://3.34.43.153:9092,plaintext://52.78.98.144:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
