spring:
  kafka:
    bootstrap-servers: plaintext://13.124.124.92:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

---
spring:
  config:
    activate:
      on-profile: client1

server:
  port: 8080

client:
  name: "CLIENT1"
---
spring:
  config:
    activate:
      on-profile: client2

server:
  port: 8081

client:
  name: "CLIENT2"
---
spring:
  config:
    activate:
      on-profile: client3

server:
  port: 8082

client:
  name: "CLIENT3"
---
spring:
  config:
    activate:
      on-profile: client4

server:
  port: 8083

client:
  name: "CLIENT4"
---
spring:
  config:
    activate:
      on-profile: client5

server:
  port: 8084

client:
  name: "CLIENT5"
---
spring:
  config:
    activate:
      on-profile: client6

server:
  port: 8085

client:
  name: "CLIENT6"
---
spring:
  config:
    activate:
      on-profile: client7

server:
  port: 8086

client:
  name: "CLIENT7"
---
spring:
  config:
    activate:
      on-profile: client8

server:
  port: 8087

client:
  name: "CLIENT8"
---
spring:
  config:
    activate:
      on-profile: client9

server:
  port: 8088

client:
  name: "CLIENT9"
---
spring:
  config:
    activate:
      on-profile: client10

server:
  port: 8089

client:
  name: "CLIENT10"
---
spring:
  config:
    activate:
      on-profile: client11

server:
  port: 8090

client:
  name: "CLIENT11"
---
spring:
  config:
    activate:
      on-profile: client12

server:
  port: 8092

client:
  name: "CLIENT12"